### ISSUE TITLE
Missing important piece of instruction in ttt-6-position-taken-rb

### ISSUE THREAD

**Issue by nscarlyon** [learn-co-curriculum/ttt-6-position-taken-rb#21]
In order to pass this lesson, the user has to pass this test: "returns true if the board has a value of "X" or "O" in the position".  This is briefly mentioned in the beginning of the lesson, but it is not mentioned at all near the end of the lesson where it is relevant. I'm sure many people can figure out where to go without the guidance (I was), but it was odd coming to the end of the lesson and discovering that there was another test not mentioned. I hope my comment made sense!

**Comment by AnnJohn** [comment]
hi @nscarlyon definitely made sense! we're not reworking this track just yet but we will soon and absolutely will note your feedback and will incorporate. in general, we make things intentionally to not be so hand-holdy. learning is a difficult experience, and we don't want to make that experience so easy that someone is plugging and chugging code that we provide them. if something is mentioned early on in a lesson, we want our learners to be aware of that and to be able to go back to that material. we want our learners to be critical thinkers (just like you!) and struggle in their learning. Learning anything isn't easy and we don't try to make that experience easy. Instead, what we make easy is support. So if someone is struggling, they can always ask for help. We're definitely fine tuning a lot but learning again is hard, and we really want our Learners to figure things out especially because we don't make them so explicit
