### ISSUE TITLE
not seeing the file in the learn ide tree structure

### ISSUE THREAD

**Issue by ICanDoAllThingThroughChrist** [learn-co-curriculum/ttt-6-position-taken-rb#33]
![no_file](https://cloud.githubusercontent.com/assets/19511967/17643640/eb73f716-6135-11e6-98f3-2e3897522d4a.png)

**Comment by AnnJohn** [comment]
hi @ICanDoAllThingThroughChrist sorry for the issue that you're having. Since this is a technical issue, please use the Ask a Question tool and someone from our team will help you out. 

Also could you file a bug report for this instead of raising an issue here (we use this space specifically for the content in lessons)? If you click on your profile pic avatar in Learn, you'll see a menu with an option to Report a Bug. Thanks!
